### ISSUE TITLE
We have company: https://cloudability.com/

### ISSUE THREAD

**Issue by jawaid** [Cloudkibo/ice#14]
Here is a commercial service on what we are trying to do with ICE.

The question is can we do a better job then them. Just with Amazon, Azure or Google. 

It will be based on two things 1) UI and ease of use 2) Analytics

https://cloudability.com/

**Comment by jekram** [comment]
This is FYI. No action required.

**Comment by sojharo** [comment]
Yes, user interface seems the thing that might beat us on any of our products. In future, one of us might have to spend good time on GUI designs and become expert or might need one person in team who is better at graphics. At least, we have better UI on KiboSupport, CloudKibo lacks many good GUI features. Yesterday, one of my class mate told me that he tried to use CloudKibo and could not understand how to make a call.

**Comment by sabachanna** [comment]
They seem more focused on aws. Azure and Google are still open grounds.

**Comment by jekram** [comment]
Sojharo:

I 110% agree with you that we would need a UI person.

In the short term we should learn and leverage the UI for Uberconference or new Go to meeting. Good UI design is a very difficult thing. But we can learn and leverage the concepts what others have done.

In the ICE case I am not too worried. I have not seen Cloudibility app yet and will soon. However, our UI will be based on High Chart or Keen.IO. It is the blend of analytics and UI.

Saba:

I think they do have Azure and Google. Since most of the cloud business is on AWS, you see AWS more on their web site.

Allah Hafiz

Jawaid
